FROM ubuntu:18.04
RUN apt-get update 
RUN apt-get install -y cmake git libgtk2.0-dev \
    libgtk-3-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev python-dev python-numpy \
    libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libdc1394-22-dev wget

RUN apt-get install -y unzip zip 
RUN wget https://github.com/opencv/opencv/archive/4.4.0.zip && ls && unzip 4.4.0.zip && cd opencv && \
    mkdir build && cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=ON \
    -D WITH_V4L=ON  -DBUILD_TIFF=ON -DWITH_GTK_2_X=ON .. && \
    make -j3 install

RUN git clone https://github.com/gabime/spdlog.git && cd spdlog && mkdir build && cd build &&  cmake .. && make -j3 install 